services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    volumes:
      - database:/var/lib/mysql/
    secrets:
      - db_password
      - db_root_password
      - db_user
      - db_name
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    volumes:
      - wordpress:/var/www/inception/
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
    secrets:
      - db_password
      - db_user
      - db_name
      - wp_user_password
      - wp_admin_password
      - wp_admin
      - wp_user

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    image: nginx
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/inception/
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hfilipe-/data/database

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hfilipe-/data/wordpress_files

networks:
  inception:
    driver: bridge

secrets:
  wp_user:
    file: ../../secrets/wp_user.txt
  wp_user_password:
    file: ../../secrets/wp_user_password.txt
  wp_admin:
    file: ../../secrets/wp_admin.txt
  wp_admin_password:
    file: ../../secrets/wp_admin_password.txt
  db_user:
    file: ../../secrets/db_user.txt
  db_password:
    file: ../../secrets/db_password.txt
  db_name:
    file: ../../secrets/db_name.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
