
services:
  wordpress:
    build: ./requirements/wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
    networks:
      - wpnet
    depends_on:
      - mariadb
      - nginx

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
    networks:
      - wpnet

  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./ssl/private.key:/etc/ssl/private/private.key:ro
    networks:
      - wpnet



volumes:
  db_data:
  wordpress_data:

networks:
  wpnet:
    driver: bridge

secrets:
  db_password:
    file: /home/hugo-lopes/42/Inception/incep/secrets/db_password.txt
  db_root_password:
    file: /home/hugo-lopes/42/Inception/incep/secrets/db_root_password.txt
