
services:

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    image:  mariadb
    volumes:
      - database:/var/lib/mysql/
    secrets:
      - db_password
      - db_root_password
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
    secrets:
      - db_password
      - wp_user_password
      - wp_admin_password

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    image: nginx
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hfilipe-/data/database

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hfilipe-/data/wordpress_files

networks:
  all:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt